language: R
sudo: false
cache: packages
warnings_are_errors: true

r:
  - release
  - devel

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      r: devel
env:
  global:
  - R_CHECK_ARGS="--timings --run-donttest"

notifications:
  email: false

r_packages:
  - covr

r_github_packages:
  - ModelOriented/ingredients
#  - ModelOriented/iBreakDown
#  - ModelOriented/DALEX

after_success:
- Rscript -e 'library(covr); codecov()'
